### ISSUE TITLE
Error when running commands from "callcommands"

### ISSUE THREAD

**Issue by flintnsteel** [Sonoran-Software/SonoranCADLuaIntegration#17]
HI, working on installing the plugins for our CAD system on my test server. I installed the pluigins as explained on the website, but when I run /911 or /511 or /311 I get the following error in console

https://i.gyazo.com/596e681da6e7242b536752bbe41b71cd.png

I haven't edited any files other than the config files

shared_functions.lua
Line 29:
"    for i,loc in ipairs(LocationCache) do"

Would appreciate any help.. Thanks

**Comment by nathanctech** [comment]
Not a bug. You don't have the `locations` plugin installed which is a requirement. Please look at our [install guide](https://info.sonorancad.com/integration-plugins/integration-plugins/available-plugins/call-commands).
