### ISSUE TITLE
core/logging.lua client-side error

### ISSUE THREAD

**Issue by Olipro** [Sonoran-Software/SonoranCADLuaIntegration#26]
An error is thrown on the client side since `os` is not made available by FiveM (intentionally)

I suggest replacing it with something like this:

```
local function LocalTime()
	local _, _, _, h, m, s = GetLocalTime()
	return '' .. h .. ':' .. m .. ':' .. s
end

local function sendConsole(level, color, message)
    local time = os and os.date("%X") or LocalTime()
    print(("[%s][SonoranCAD:%s%s^7]%s %s^0"):format(time, color, level, color, message))
end
```

**Comment by nathanctech** [comment]
Ah yes...I totally forgot `os` was not available to the client. Thanks for the report, I'll make the changes for the next bugfix release.
