### ISSUE TITLE
GetPlayerIdentifierByType instead of current GetPlayerIdentifier

### ISSUE THREAD

**Issue by hickorysb** [Sonoran-Software/SonoranCADLuaIntegration#80]
`GetPlayerIdentifierByType` is now a native that exists.

```lua
GetPlayerIdentifierByType(source, type)
```

I haven't checked performance between the two, but I'd assume that the `ByType` function would be faster than the current loop method.

To maintain compatibility with existing code as much as possible the current function in `shared_functions.lua` could be updated from:
```lua
function GetIdentifiers(player)
    local ids = {}
    for _, id in ipairs(GetPlayerIdentifiers(player)) do
        local split = stringsplit(id, ":")
        ids[split[1]] = split[2]
    end
    --debugLog("Returning "..json.encode(ids))
    return ids
end
```
to:
```lua
function GetIdentifiers(player)
    let ids = {}
    ids[Config.primaryIdentifier] = GetPlayerIdentifierByType(player, Config.primaryIdentifier)
    --debugLog("Returning "..json.encode(ids))
    return ids
end
```

This allows all calls to `GetIdentifiers` to remain functional while using the more recent native. The earliest known server version to include this is `6497`. If after receiving feedback from those in charge of maintaining this repo, there is interest in this update I will create a PR with the modification.

**Comment by nathanctech** [comment]
The function returns a table of all available IDs rather than just the primary one, so the native here would not accomplish that task since we would still have to loop to return all identifiers.

**Comment by hickorysb** [comment]
The way I rewrote the function still returns a table that contains the primary identifier type as a table key and the identifier as the value. So it is compatible with how the rest of the plugins already use the `GetIdentifiers` function.

**Comment by Fireant456** [comment]
Moved issue to v3 branch
