### ISSUE TITLE
Race Condition getting web_baseUrl convar for use in Bodycam integration

### ISSUE THREAD

**Issue by Fireant456** [Sonoran-Software/SonoranCADLuaIntegration#87]
As reported in #86, it appears that the web_baseUrl convar set by FXServer is sometimes not set when the framework starts. leading to an issue with the bodycam integration not functioning until a resource restart. User suggests a fallback value but as mentioned in the PR, it is likely not the best option due to:

1. Requiring server admin to set a fallback value (good for further edge cases, but not a good solution for the broader user base)
2. May be incorrect when server hosting or configuration is changed, no automation is possible with a static value like this
3. Not being proxied by CFX.re Nucleus

I propose implementing a looping check on this convar if it is not set when booting, further logging can be implemented to throw errors if the value is not found after 5-10 attempts after 15-60 seconds. @Jordan2139 would love your thoughts on this as this value only seems to be used for the bodycam integration at least from my searching of our github org.

**Comment by SonoranBrian** [comment]
Patched with v2.9.26
