### ISSUE TITLE
Config option: `bodycamOverlayEnabled` has no effect

### ISSUE THREAD

**Issue by coleminer0112** [Sonoran-Software/SonoranCADLuaIntegration#89]
Noticed this issue in-game after synchronizing bodycam enabled state with a custom bodycam overlay and attempting to disable sonorancad's overlay icon. A search through the resource indicated bodycamOverlayEnabled is never found in any conditional statements on client nor server side.

Due to the fact I have a bodycam overlay which displays in-character information, I'd like to be able to disable this sonoran overlay but it appears despite the setting being `false`

Suggested fix would be @ lines 158, 146, 112 of core/client.lua adding a conditional to check if Config.bodycamOverlayEnabled == true. If you'd like I can PR this change myself, just let me know

![image](https://github.com/Sonoran-Software/SonoranCADLuaIntegration/assets/61920219/edadc2e8-95e3-4d22-813d-e4fe5c5cd541)

**Comment by SonoranBrian** [comment]
Please submit this as a PR, along with the version bumps for release.

We'll review and release.

Thank you!
